// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { fetchConfig } from "../shared";
import { Sms } from "./otp_sms";

export class OTPs {
  private fetchConfig: fetchConfig;
  sms: Sms;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
    this.sms = new Sms(this.fetchConfig);
  }
}
