// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { fetchConfig } from "../shared";
import { request } from "../shared";
import { Session } from "./sessions";
import { User } from "./users";

// Request type for `cryptoWallets.authenticate`.
export interface CryptoWalletsAuthenticateRequest {
  /**
   * The type of wallet to authenticate. Currently `ethereum` and `solana` are supported. Wallets for any
   * EVM-compatible chains (such as Polygon or BSC) are also supported and are grouped under the `ethereum`
   * type.
   */
  crypto_wallet_type: string;
  // The crypto wallet address to authenticate.
  crypto_wallet_address: string;
  // The signature from the message challenge.
  signature: string;
  // The `session_token` associated with a User's existing Session.
  session_token?: string;
  /**
   * Set the session lifetime to be this many minutes from now. This will start a new session if one doesn't
   * already exist,
   *   returning both an opaque `session_token` and `session_jwt` for this session. Remember that the
   * `session_jwt` will have a fixed lifetime of
   *   five minutes regardless of the underlying session duration, and will need to be refreshed over time.
   *
   *   This value must be a minimum of 5 and a maximum of 527040 minutes (366 days).
   *
   *   If a `session_token` or `session_jwt` is provided then a successful authentication will continue to
   * extend the session this many minutes.
   *
   *   If the `session_duration_minutes` parameter is not specified, a Stytch session will not be created.
   */
  session_duration_minutes?: number;
  // The `session_jwt` associated with a User's existing Session.
  session_jwt?: string;
  /**
   * Add a custom claims map to the Session being authenticated. Claims are only created if a Session is
   * initialized by providing a value in `session_duration_minutes`. Claims will be included on the Session
   * object and in the JWT. To update a key in an existing Session, supply a new value. To delete a key,
   * supply a null value.
   *
   *   Custom claims made with reserved claims ("iss", "sub", "aud", "exp", "nbf", "iat", "jti") will be
   * ignored. Total custom claims size cannot exceed four kilobytes.
   */
  session_custom_claims?: Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any
}

// Response type for `cryptoWallets.authenticate`.
export interface CryptoWalletsAuthenticateResponse {
  /**
   * Globally unique UUID that is returned with every API call. This value is important to log for debugging
   * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
   */
  request_id: string;
  // The unique ID of the affected User.
  user_id: string;
  // A secret token for a given Stytch Session.
  session_token: string;
  // The JSON Web Token (JWT) for a given Stytch Session.
  session_jwt: string;
  /**
   * The `user` object affected by this API call. See the
   * [Get user endpoint](https://stytch.com/docs/api/get-user) for complete response field details.
   */
  user: User;
  /**
   * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
   * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
   */
  status_code: number;
  /**
   * If you initiate a Session, by including `session_duration_minutes` in your authenticate call, you'll
   * receive a full Session object in the response.
   *
   *   See [GET sessions](https://stytch.com/docs/api/session-get) for complete response fields.
   *
   */
  session?: Session;
}

// Request type for `cryptoWallets.authenticateStart`.
export interface CryptoWalletsAuthenticateStartRequest {
  /**
   * The type of wallet to authenticate. Currently `ethereum` and `solana` are supported. Wallets for any
   * EVM-compatible chains (such as Polygon or BSC) are also supported and are grouped under the `ethereum`
   * type.
   */
  crypto_wallet_type: string;
  // The crypto wallet address to authenticate.
  crypto_wallet_address: string;
  // The unique ID of a specific User.
  user_id?: string;
  // The `session_token` associated with a User's existing Session.
  session_token?: string;
  // The `session_jwt` associated with a User's existing Session.
  session_jwt?: string;
}

// Response type for `cryptoWallets.authenticateStart`.
export interface CryptoWalletsAuthenticateStartResponse {
  /**
   * Globally unique UUID that is returned with every API call. This value is important to log for debugging
   * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
   */
  request_id: string;
  // The unique ID of the affected User.
  user_id: string;
  // A challenge string to be signed by the wallet in order to prove ownership.
  challenge: string;
  // In `login_or_create` endpoints, this field indicates whether or not a User was just created.
  user_created: boolean;
  /**
   * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
   * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
   */
  status_code: number;
}

export class CryptoWallets {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Initiate the authentication of a crypto wallet. After calling this endpoint, the user will need to sign
   * a message containing only the returned `challenge` field.
   * @param data {@link CryptoWalletsAuthenticateStartRequest}
   * @returns {@link CryptoWalletsAuthenticateStartResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  authenticateStart(
    data: CryptoWalletsAuthenticateStartRequest
  ): Promise<CryptoWalletsAuthenticateStartResponse> {
    const headers: Record<string, string> = {};
    return request<CryptoWalletsAuthenticateStartResponse>(this.fetchConfig, {
      method: "POST",
      url: `/v1/crypto_wallets/authenticate/start`,
      headers,
      data,
    });
  }

  /**
   * Complete the authentication of a crypto wallet by passing the signature.
   * @param data {@link CryptoWalletsAuthenticateRequest}
   * @returns {@link CryptoWalletsAuthenticateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  authenticate(
    data: CryptoWalletsAuthenticateRequest
  ): Promise<CryptoWalletsAuthenticateResponse> {
    const headers: Record<string, string> = {};
    return request<CryptoWalletsAuthenticateResponse>(this.fetchConfig, {
      method: "POST",
      url: `/v1/crypto_wallets/authenticate`,
      headers,
      data,
    });
  }
}
