// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import {} from "../shared/method_options";
import { AddressInformation, DomainInformation } from "./fraud";
import { fetchConfig } from "../shared";
import { request } from "../shared";

// Request type for `fraud.email.risk`.
export interface FraudEmailRiskRequest {
  // The email address to check.
  email_address: string;
}

// Response type for `fraud.email.risk`.
export interface FraudEmailRiskResponse {
  /**
   * Globally unique UUID that is returned with every API call. This value is important to log for debugging
   * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
   */
  request_id: string;
  // Information about the email address.
  address_information: AddressInformation;
  // Information about the email domain.
  domain_information: DomainInformation;
  /**
   * The suggested action based on the attributes of the email address. The available actions are:
   *   * `ALLOW` - This email is most likely safe to send to and not fraudulent.
   *   * `BLOCK` - This email is invalid or exhibits signs of fraud. We recommend blocking the end user.
   *   * `CHALLENGE` - This email has some potentially fraudulent attributes. We recommend increased friction
   * such as 2FA or other forms of extended user verification before allowing the privileged action to
   * proceed.
   *
   */
  action: "ALLOW" | "CHALLENGE" | "BLOCK" | string;
  // A score from 0 to 100 indicating how risky the email is. 100 is the most risky.
  risk_score: number;
  /**
   * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
   * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
   */
  status_code: number;
}

export class Email {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Get risk information for a specific email address.
   * The response will contain a recommended action (`ALLOW`, `BLOCK`, or `CHALLENGE`) and a more granular
   * `risk_score`.
   * You can also check the `address_information` and `domain_information` fields for more information about
   * the email address and email domain.
   *
   * This feature is in beta. Reach out to us
   * [here](mailto:fraud-team@stytch.com?subject=Email_Intelligence_Early_Access) if you'd like to request
   * early access.
   * @param data {@link FraudEmailRiskRequest}
   * @returns {@link FraudEmailRiskResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  risk(data: FraudEmailRiskRequest): Promise<FraudEmailRiskResponse> {
    const headers: Record<string, string> = {};
    return request<FraudEmailRiskResponse>(this.fetchConfig, {
      method: "POST",
      url: `/v1/email/risk`,
      baseURLType: "FRAUD",
      headers,
      data,
    });
  }
}
