// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import {} from "../shared/method_options";
import { fetchConfig } from "../shared";
import { Fingerprint } from "./fraud_fingerprint";
import { Rules } from "./fraud_rules";

export interface ASNProperties {
  // The Autonomous System Number of the user's network.
  asn: string;
  // Public name associated with the ASN.
  name: string;
  // The CIDR block associated with the ASN.
  network: string;
}

export interface BrowserProperties {
  // The user agent of the user's browser.
  user_agent: string;
}

export interface Fingerprints {
  // Combination of signals associated with a specific network commonly known as TLS fingerprinting.
  network_fingerprint: string;
  // Combinations of signals to identify an operating system and architecture.
  hardware_fingerprint: string;
  // Combination of signals to identify a browser and its specific version.
  browser_fingerprint: string;
  // Cookie-less way of identifying a unique user.
  visitor_fingerprint: string;
  // The cookie stored on the user's device that uniquely identifies them.
  visitor_id?: string;
  // Combination of VisitorID and NetworkFingerprint to create a clear identifier of a browser.
  browser_id?: string;
}

export interface IPGeoProperties {
  // The city where the IP is located.
  city: string;
  // The region where the IP is located.
  region: string;
  // The country where the IP is located.
  country: string;
}

export interface Metadata {
  // An external ID, such as a user ID, that you wish to associate with the telemetry ID.
  external_id?: string;
  // The organization ID you wish to associate with the telemetry ID.
  organization_id?: string;
  // The user action, such as 'login', that you wish to associate with the telemetry ID.
  user_action?: string;
}

export interface NetworkProperties {
  // The IP address of the user.
  ip_address: string;
  // Information about the network's ASN (Autonomous System Number).
  asn: ASNProperties;
  // Information about the geolocation of the user's IP address.
  ip_geolocation: IPGeoProperties;
  // Whether the user is using a proxy.
  is_proxy: boolean;
  // Whether the user is using a VPN.
  is_vpn: boolean;
}

export interface Properties {
  network_properties: NetworkProperties;
  browser_properties: BrowserProperties;
}

export interface Rule {
  /**
   * The rule type. The possible values are `VISITOR_ID`, `BROWSER_ID`, `VISITOR_FINGERPRINT`,
   * `BROWSER_FINGERPRINT`, `HARDWARE_FINGERPRINT`, `NETWORK_FINGERPRINT`, `CIDR_BLOCK`, `ASN`, or
   * `COUNTRY_CODE`.
   */
  rule_type:
    | "VISITOR_ID"
    | "BROWSER_ID"
    | "VISITOR_FINGERPRINT"
    | "BROWSER_FINGERPRINT"
    | "HARDWARE_FINGERPRINT"
    | "NETWORK_FINGERPRINT"
    | "CIDR_BLOCK"
    | "ASN"
    | "COUNTRY_CODE"
    | string;
  // The action (`ALLOW`, `BLOCK`, or `CHALLENGE`) that will be returned for this rule.
  action: "ALLOW" | "CHALLENGE" | "BLOCK" | "NONE" | string;
  /**
   * The time when the rule was created. Values conform to the RFC 3339 standard and are expressed in UTC,
   * e.g. `2021-12-29T12:33:09Z`.
   */
  created_at: string;
  // The visitor ID that a rule was set for.
  visitor_id?: string;
  // The browser ID that a rule was set for.
  browser_id?: string;
  // The visitor fingerprint that a rule was set for.
  visitor_fingerprint?: string;
  // The browser fingerprint that a rule was set for.
  browser_fingerprint?: string;
  // The hardware fingerprint that a rule was set for.
  hardware_fingerprint?: string;
  // The network fingerprint that a rule was set for.
  network_fingerprint?: string;
  /**
   * The CIDR block that a rule was set for. If an end user's IP address is within this CIDR block, this rule
   * will be applied.
   */
  cidr_block?: string;
  // The country code that a rule was set for.
  country_code?: string;
  // The ASN that a rule was set for.
  asn?: string;
  // A description for the rule.
  description?: string;
  /**
   * The timestamp when the rule expires. Values conform to the RFC 3339 standard and are expressed in UTC,
   * e.g. `2021-12-29T12:33:09Z`.
   */
  expires_at?: string;
  /**
   * The time when the rule was last updated. Will be null if the rule has never been updated. Values conform
   * to the RFC 3339 standard and are expressed in UTC, e.g. `2021-12-29T12:33:09Z`.
   */
  last_updated_at?: string;
}

export interface Verdict {
  /**
   * The suggested action based on the fingerprint review. The available actions are:
   *   * `ALLOW` - This is a known valid device grouping or device profile that is part of the default ALLOW
   * listed set of known devices by Stytch. This grouping is made up of verified device profiles that match
   * the characteristics of known/authentic traffic origins
   *   * `BLOCK` - This is a known bad or malicious device profile that is undesirable and should be blocked
   * from completing the privileged action in question
   *   * `CHALLENGE` - This is an unknown or potentially malicious device that should be put through
   * increased friction such as 2FA or other forms of extended user verification before allowing the
   * privileged action to proceed
   *
   */
  action: "ALLOW" | "CHALLENGE" | "BLOCK" | string;
  /**
   * A set of contextual clues to inform why a `CHALLENGE` or `BLOCK` action was suggested. For a list of
   * possible Reasons, please [contact support](mailto:support@stytch.com).
   */
  reasons: string[];
  // The operating system and architecture that took the fingerprint.
  detected_device_type: string;
  /**
   * The assessment of whether this is an authentic device. It will be false if hardware or browser deception
   * is detected.
   */
  is_authentic_device: boolean;
  /**
   * The type of rule match that was applied (e.g. `VISITOR_ID`), if any. This field will only be present if
   * there is a `RULE_MATCH` reason in the list of verdict reasons.
   */
  rule_match_type?:
    | "VISITOR_ID"
    | "BROWSER_ID"
    | "VISITOR_FINGERPRINT"
    | "BROWSER_FINGERPRINT"
    | "HARDWARE_FINGERPRINT"
    | "NETWORK_FINGERPRINT"
    | "CIDR_BLOCK"
    | "ASN"
    | "COUNTRY_CODE"
    | string;
  /**
   * The rule that was applied (e.g. a specific visitor ID value), if any. This field will only be present if
   * there is a `RULE_MATCH` reason in the list of verdict reasons.
   */
  rule_match_identifier?: string;
}

export class Fraud {
  private fetchConfig: fetchConfig;
  fingerprint: Fingerprint;
  rules: Rules;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
    this.fingerprint = new Fingerprint(this.fetchConfig);
    this.rules = new Rules(this.fetchConfig);
  }
}
