import { BaseClient, ClientConfig } from "../shared/client";
import { Discovery } from "./discovery";
import { Fraud } from "../b2c/fraud";
import { Impersonation } from "./impersonation";
import { JwtConfig } from "../shared/sessions";
import { M2M } from "../b2c/m2m";
import { MagicLinks } from "./magic_links";
import { OAuth } from "./oauth";
import { Organizations } from "./organizations";
import { OTPs } from "./otp";
import { Passwords } from "./passwords";
import { Project } from "../b2c/project";
import { RBAC } from "./rbac";
import { RecoveryCodes } from "./recovery_codes";
import { SCIM } from "./scim";
import { Sessions } from "./sessions";
import { SSO } from "./sso";
import { TOTPs } from "./totps";
import { IDP } from "./idp";
export declare class B2BClient extends BaseClient {
    protected jwtConfig: JwtConfig;
    discovery: Discovery;
    fraud: Fraud;
    impersonation: Impersonation;
    m2m: M2M;
    magicLinks: MagicLinks;
    oauth: OAuth;
    otps: OTPs;
    organizations: Organizations;
    passwords: Passwords;
    project: Project;
    rbac: RBAC;
    recoveryCodes: RecoveryCodes;
    scim: SCIM;
    sso: SSO;
    sessions: Sessions;
    totps: TOTPs;
    idp: IDP;
    constructor(config: ClientConfig);
}
